SINT: wait for notification filter to propagate
igniterealtime/Smack pull request #440
Opened 2020-10-12 15:21 UTC by guusdk

Several PEP-based Smack Integration Test Framework tests have been disabled in the CI pipeline for Openfire, as they frequently, but inconsistently, failed. The changes in this PR address that.

Each of these tests depend on a pubsub notification filter to be in place, to allow the intended recipient to receive a notification. A race condition exists where the setting of that filter competes with the publishing of data.

The changes in this PR add a synchronization point to explicitly wait for the filter to have been set, before proceeding to execute the test.

2020-10-14 18:19 UTC, vanitasvitae requested changes
What is that `tatus` file that got changed?

2020-10-15 07:52 UTC, guusdk commented
Unsure how exactly I managed to get that `tatus` file committed. It's gone now.

2021-03-06 14:40 UTC, Flowdalic commented
Could you rebase this on the latest master? I think this introduces changes to existing tests and adds new ones. Ideally this would be in two separate commits

2021-11-04 11:32 UTC, guusdk commented
Rebased to current master, and refactored to make use of the change introduced in https://github.com/igniterealtime/Smack/pull/441

2021-12-12 20:46 UTC, Flowdalic commented
Merged as https://github.com/igniterealtime/Smack/commit/819ed87a178e71c6c40b70d6a5f079751337b51f

2021-12-12 20:46 UTC, closed without merging