Unnecessary Exception is thrown when pub sub configure node is empty,…
igniterealtime/Smack pull request #471
Opened 2021-04-26 17:28 UTC by annovanvliet

… for instance in case of an auth error.

2021-04-26 19:37 UTC, Flowdalic requested changes
Can you share the stanza that triggers this? Also ideally add a test case for this.

2021-04-26 19:37 UTC, Flowdalic commented on smack-extensions/src/main/java/org/jivesoftware/smackx/pubsub/provider/FormNodeProvider.java
> +        if ( !content.isEmpty() ) {
"If content is empty, then return null" is easier to read.

2021-04-27 09:26 UTC, annovanvliet commented
An example is the following returned from OF:
<iq type="error" id="6LXNC-48" from="pubsub.openfire.xmpp.test" to="anno@openfire.xmpp.test/5dsi4g084a">
  <pubsub xmlns="http://jabber.org/protocol/pubsub#owner">
    <configure node="fdp/submitted/spot_report"/>
  </pubsub>
  <error code="403" type="auth">
    <forbidden xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
  </error>
</iq>

2021-04-27 14:23 UTC, Flowdalic commented
It appears to me the correct fix to this would be to allow `null` as `DataForm` argument to `FormNode`.

2021-08-23 16:02 UTC, closed without merging