[sint] new presence subscription tests
igniterealtime/Smack pull request #481
Opened 2021-06-30 19:04 UTC by guusdk

This adds a few basic tests that verify that presence subscription stanzas are received 'as intended', notably when they include extension elements.

2021-06-30 19:59 UTC, guusdk commented
After grudgingly applying two other 'improvements', this PR fails once again on a Checkstyle-based rule. I'm giving up.

2022-08-03 12:48 UTC, Flowdalic requested changes
Please find my review inline.

I think I've mentioned this before, but some of those tests are more towards testing server behavior and not really about integration tests. I guess a few simple ones are fine for Smack itself, but if you keep the integration tests coming that primarly test server behavior, then we really should think about establishing a separate xmpp-c2s-server-integration-test project where those tests reside in. Such a project can easily be based on, and exploit, Smack's integration test framework.

2022-08-03 12:48 UTC, Flowdalic commented on smack-integration-test/src/main/java/org/jivesoftware/smack/subscription/SubscriptionIntegrationTest.java
> +                    if (!(stanza instanceof Presence)) {
Use idiomatic Smack filters.

2022-08-03 12:48 UTC, Flowdalic commented on smack-integration-test/src/main/java/org/jivesoftware/smack/subscription/SubscriptionIntegrationTest.java
> +                stanza -> {
Use idiomatic Smack filters.

2022-08-03 12:48 UTC, Flowdalic commented on smack-integration-test/src/main/java/org/jivesoftware/smack/subscription/SubscriptionIntegrationTest.java
> +        ((AbstractXMPPConnection) conOne).disconnect();
As above, this should probably be a low level integration test.

2023-11-26 12:23 UTC, guusdk commented
I've applied the feedback and rebased to the current HEAD of the Master branch for good measure.

Using a low-level test is less straight-forward if it's desirable to be able to make use of provisioned user accounts, or a mix of connected and unconnected connections. I've experimented with using `UnconnectedConnectionSource` and taking usernames from the configuration, but could not get that to work. As a result, this test still depends on two _connected_ resources, one of which is disconnected at the start of the tests. Those tests now _do_ inherit from Low-Level, which is at least something, I suppose.

2024-03-08 13:30 UTC, Flowdalic requested changes
I think all of this belongs rather into smack-sint-server-extensions.

2024-03-08 13:30 UTC, Flowdalic commented on smack-integration-test/src/main/java/org/jivesoftware/smack/subscription/LowLevelSubscriptionIntegrationTest.java
> +    public void testSubscriptionRequestOffline(final AbstractXMPPConnection conOne,
Please correct me if I am wrong (for this and all potential following statements), but this seems to test primarily a server functionality (i.e., that a presence subscription test send while the recipient is offline, is delivered once the recipient comes online).

As such, it is probably not a good fit for Smack and instead for smack-sinttest-server-extensions

2024-03-08 13:30 UTC, Flowdalic commented on smack-integration-test/src/main/java/org/jivesoftware/smack/subscription/LowLevelSubscriptionIntegrationTest.java
> +    public void testSubscriptionRequestOfflineWithExtension(final AbstractXMPPConnection conOne,
Dito

2024-03-08 14:02 UTC, guusdk commented
The tests to be added in this PR are now being added to the smack-sint-server-extensions project instead: https://github.com/XMPP-Interop-Testing/smack-sint-server-extensions/pull/6

2024-03-08 14:02 UTC, closed without merging